### PR TITLE
Export with dlls

### PR DESCRIPTION
**Pull request by derekdai**
Add `.gdnlib` for `.gdns` which is needed by godot while exporting

### CODE REVIEW

**Comment by geekrelief** [comment]
Thanks! I'll look into your PRs soon.

**Comment by derekdai** [comment]
Thank you. If there are any coding style issues, please let me know.

**Comment by geekrelief** [comment]
I'm a little confused or maybe I need some sleep. :)  You have several branches, and it seems like there are similar commits between.

**Comment by geekrelief** [comment]
Merged and pushed. Can you pull and double check everything is working for you? Thanks.

**Pull request merged**
